# SPDX-License-Identifier: MIT-0
---
namespace: brocktech

name: gitea

version: 1.0.0

readme: README.md

authors:
  - Curtis Jones <curtis.jones@brocku.ca>

description: Gsbtech utilities for dealing with the gitea api.

license_file: LICENSE

tags:
  - git
  - gitea

dependencies: {}

repository: https://github.com/brocktech/ansible-gitea

documentation: https://github.com/brocktech/ansible-gitea

homepage: https://github.com/brocktech/ansible-gitea

issues: https://github.com/brocktech/ansible-gitea/issues

build_ignore:
  - .github
  - .gitea
  - .gitignore
  - flake.nix
  - flake.lock
  - .direnv
  - .envrc
  - changelog
  - out
